all:
	(cd ../..; cd examples ; make clean all > /dev/null)
	(cd attributes && make clean all)
	(cd sem_enum && make clean all)
	(cd sem_ext_decls && make clean all)
	(cd bug21_sem_typedef && make clean all)
	(cd bug22_file_permission_cpp && make clean all)
