all:
	(cd ../..; cd examples ; make clean all > /dev/null)

	(cd attributes && make clean all)

	(cd analysis_enum && make clean all)
	(cd analysis_ext_decls && make clean all)
	(cd analysis_local_decls && make clean all)
	(cd analysis_type_check && make clean all)

	(cd bug21_sem_typedef && make clean all)
	(cd bug22_file_permission_cpp && make clean all)
	(cd bug30_preserve_int_repr && make)