#!/bin/sh
# Configuration
TEST_DIR=tmp/language_c
# Run a regression test before pushing to code.haskell.org
# People don't like code that doesn't compile
function die() { 
    echo "*** Regression test failed: $1 ***" 1>&2; exit 1 
}
if [ ! -d $TEST_DIR ] ; then 
    die "'$TEST_DIR' directory does not exist (needs to be a checkout of HEAD)"
fi
cd $TEST_DIR
darcs pull || die "darcs pull failed"
echo "Building via cabal"
cabal clean 
cabal configure || die "cabal configure failed"
cabal build || die "cabal build failed"
cabal haddock || die "cabal haddock failed"
echo "Finished building via cabal"
cd test
echo "Building test suite"
make || die "make failed in /test"
(cd suite && yes | bash run-dg.sh) || die \
    "run-dg.sh failed - make sure there is a symlink or copy to the gcc.dg testsuite in $TMPDIR/test/suite"
( cd results && ../bin/RenderTests regression *dat) || die "rendering tests failed"
open results/index.html
exit 0

